import { auth } from '@/auth';
import type { Metadata } from 'next';
import { Provider } from '../providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await auth();
  return <Provider session={session}>{children}</Provider>;
}
